---
model:
  vwf/model/threejs:
  vwf/model/blockly:
  vwf/model/sound:
view:
  vwf/view/threejs: "#vwf-root"
<<<<<<< HEAD
<<<<<<< HEAD
  vwf/view/blockly: { "blocklyPath": './source/blockly/' }
=======
  vwf/view/blockly: { "blocklyPath": './source/blockly/', "toolbox": 'toolbox' }
>>>>>>> FETCH_HEAD
=======
  vwf/view/blockly: { "blocklyPath": './source/blockly/', "toolbox": 'toolbox' }
>>>>>>> FETCH_HEAD
  vwf/view/sound: 
  vwf/view/editor:
  